theme = "onedark"

[editor]
cursorline = true
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "¬"

[editor.lsp]
display-inlay-hints = true
